version: "{build}"
image: Visual Studio 2017

skip_tags: true

environment:
  matrix:
    - JAVA_HOME: C:/Program Files/Java/jdk1.8.0

build_script:
  - mvnw.cmd clean verify -B -V

cache:
  - C:/Users/appveyor/.m2
