language: minimal
dist: trusty
sudo: true

matrix:
  include:
    - os: linux
      before_install:
        - sudo bash -c 'if [ `cat /proc/net/if_inet6 | wc -l` = "0" ]; then echo "Enabling IPv6" ; sysctl net.ipv6.conf.all.disable_ipv6=0 ; sysctl net.ipv6.conf.default.disable_ipv6=0 ; sysctl net.ipv6.conf.lo.disable_ipv6=0 ; fi'
        - mkdir $HOME/openjdk8
        - curl -L 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=linux&type=jdk&release=latest&arch=x64' | tar zx --strip-components=1 --directory $HOME/openjdk8
        - export JAVA_HOME=$HOME/openjdk8

    - os: osx
      before_install:
        - mkdir $HOME/openjdk8
        - curl -L 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=mac&type=jdk&release=latest&arch=x64' | tar zx --strip-components=1  --directory $HOME/openjdk8
        - export JAVA_HOME=$HOME/openjdk8/Contents/Home

install:
  - ./mvnw clean install -B -V -DskipTests

script:
  - ./mvnw clean install

after_failure:
  - ./surefire-reports.sh

cache:
  directories:
    - $HOME/.m2
