language: minimal
dist: trusty
sudo: true

stages:
  - install
  - test
  - name: deploy
    if: tag IS present

cache:
  directories:
    - $HOME/.m2
    - $HOME/openjdk8

env:
  global: JAVA_HOME=$HOME/openjdk8

jobs:
  include:
    - stage: install
      os: linux
      script:
        - rm -rf $JAVA_HOME
        - mkdir $JAVA_HOME
        - curl -L 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=linux&type=jdk&release=latest&arch=x64' | tar zx --strip-components=1 --directory $JAVA_HOME
    - os: osx
      script:
        - rm -rf $JAVA_HOME
        - mkdir $JAVA_HOME
        - curl -L 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=mac&type=jdk&release=latest&arch=x64' | tar zx --strip-components=3  --directory $JAVA_HOME
    - stage: test
      os: linux
      script:
        - ./mvnw clean verify -B -V
      after_failure: ./surefire-reports.sh
    - os: osx
      script:
        - ./mvnw clean verify -B -V
      after_failure: ./surefire-reports.sh
    - stage: deploy
      os: linux
      script:
        - ./mvnw clean verify -DskipTests -Pdocs
      after_failure: ./surefire-reports.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: embedded-cassandra-docs/target/generated-docs/

